remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: My Security Writeups
description: HackTheBox and CTF writeups by Alex
baseurl: "/cyber-write-ups"

collections:
  writeups:
    output: true
    permalink: /writeups/:path/